version: '3'
services:
  db:
    image: postgres
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db_net

  backend:
    image: alionski/lab2_backend:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - images_vol:/usr/src/lab_2/static/images
    depends_on:
      - db
    networks:
      - db_net
      - backend_net

  frontend:
    image: nginx:1.13-alpine
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - backend_net

networks:
  db_net:
  backend_net:

volumes:
  images_vol:

