version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  backend:
    image: lab/backend
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/lab_2
    depends_on:
      - db

  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 80:80